--
-- PostgreSQL database dump
--

-- Dumped from database version 16.1
-- Dumped by pg_dump version 16.1

-- Started on 2024-07-11 20:51:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16554)
-- Name: answer_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.answer_table (
    is_correct boolean,
    answer_id bigint NOT NULL,
    question_id bigint NOT NULL,
    answer_text character varying(255)
);


ALTER TABLE public.answer_table OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16553)
-- Name: answer_table_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.answer_table ALTER COLUMN answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answer_table_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16626)
-- Name: answer_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.answer_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.answer_table_seq OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16560)
-- Name: form_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.form_table (
    form_id bigint NOT NULL,
    description character varying(255),
    title character varying(255)
);


ALTER TABLE public.form_table OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16559)
-- Name: form_table_form_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.form_table ALTER COLUMN form_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.form_table_form_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16627)
-- Name: form_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.form_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.form_table_seq OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16568)
-- Name: question_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.question_table (
    form_id bigint NOT NULL,
    question_id bigint NOT NULL,
    question_text character varying(255)
);


ALTER TABLE public.question_table OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16567)
-- Name: question_table_question_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.question_table ALTER COLUMN question_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.question_table_question_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16628)
-- Name: question_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.question_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.question_table_seq OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16574)
-- Name: user_answer_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_answer_table (
    attempt integer NOT NULL,
    answer_id bigint NOT NULL,
    question_id bigint NOT NULL,
    user_answer_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_answer_table OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16629)
-- Name: user_answer_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_answer_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_answer_table_seq OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16573)
-- Name: user_answer_table_user_answer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_answer_table ALTER COLUMN user_answer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_answer_table_user_answer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16580)
-- Name: user_ranking_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_ranking_table (
    total_score double precision,
    ranking_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_ranking_table OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16579)
-- Name: user_ranking_table_ranking_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_ranking_table ALTER COLUMN ranking_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_ranking_table_ranking_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16630)
-- Name: user_ranking_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_ranking_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_ranking_table_seq OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16588)
-- Name: user_table; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_table (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    username character varying(255),
    roles character varying(255)
);


ALTER TABLE public.user_table OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16587)
-- Name: user_table_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_table ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_table_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16631)
-- Name: user_table_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_table_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_table_seq OWNER TO postgres;

--
-- TOC entry 4666 (class 2606 OID 16558)
-- Name: answer_table answer_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer_table
    ADD CONSTRAINT answer_table_pkey PRIMARY KEY (answer_id);


--
-- TOC entry 4668 (class 2606 OID 16566)
-- Name: form_table form_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.form_table
    ADD CONSTRAINT form_table_pkey PRIMARY KEY (form_id);


--
-- TOC entry 4670 (class 2606 OID 16572)
-- Name: question_table question_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_table
    ADD CONSTRAINT question_table_pkey PRIMARY KEY (question_id);


--
-- TOC entry 4672 (class 2606 OID 16578)
-- Name: user_answer_table user_answer_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answer_table
    ADD CONSTRAINT user_answer_table_pkey PRIMARY KEY (user_answer_id);


--
-- TOC entry 4674 (class 2606 OID 16584)
-- Name: user_ranking_table user_ranking_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ranking_table
    ADD CONSTRAINT user_ranking_table_pkey PRIMARY KEY (ranking_id);


--
-- TOC entry 4676 (class 2606 OID 16586)
-- Name: user_ranking_table user_ranking_table_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ranking_table
    ADD CONSTRAINT user_ranking_table_user_id_key UNIQUE (user_id);


--
-- TOC entry 4678 (class 2606 OID 16594)
-- Name: user_table user_table_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_table
    ADD CONSTRAINT user_table_pkey PRIMARY KEY (id);


--
-- TOC entry 4681 (class 2606 OID 16615)
-- Name: user_answer_table fk1cwhall6yi7mvh90o2qhcpr00; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answer_table
    ADD CONSTRAINT fk1cwhall6yi7mvh90o2qhcpr00 FOREIGN KEY (user_id) REFERENCES public.user_table(id);


--
-- TOC entry 4680 (class 2606 OID 16600)
-- Name: question_table fk1pb2yu7dvt0chvrcbnho4x6e9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.question_table
    ADD CONSTRAINT fk1pb2yu7dvt0chvrcbnho4x6e9 FOREIGN KEY (form_id) REFERENCES public.form_table(form_id);


--
-- TOC entry 4682 (class 2606 OID 16605)
-- Name: user_answer_table fkaxmo325guegttqj6yc4x3nvpb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answer_table
    ADD CONSTRAINT fkaxmo325guegttqj6yc4x3nvpb FOREIGN KEY (answer_id) REFERENCES public.answer_table(answer_id);


--
-- TOC entry 4684 (class 2606 OID 16620)
-- Name: user_ranking_table fkcb7hf75hrko90f7h8pgdin954; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ranking_table
    ADD CONSTRAINT fkcb7hf75hrko90f7h8pgdin954 FOREIGN KEY (user_id) REFERENCES public.user_table(id);


--
-- TOC entry 4683 (class 2606 OID 16610)
-- Name: user_answer_table fkjjtl4rnvi4votac6v20booylr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_answer_table
    ADD CONSTRAINT fkjjtl4rnvi4votac6v20booylr FOREIGN KEY (question_id) REFERENCES public.question_table(question_id);


--
-- TOC entry 4679 (class 2606 OID 16595)
-- Name: answer_table fkp690se8k5dqvjid6xrq9ohgti; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.answer_table
    ADD CONSTRAINT fkp690se8k5dqvjid6xrq9ohgti FOREIGN KEY (question_id) REFERENCES public.question_table(question_id);


-- Completed on 2024-07-11 20:51:07

--
-- PostgreSQL database dump complete
--

